### ISSUE TITLE
Thoughts on how to convert this Bash HG to Zsh?

### ISSUE THREAD

**Issue by misterhtmlcss** [iarkhanhelsky/oh-my-zsh-hg-prompt#1]
I found (what I believe) is a Bash instruction on how to include the mercurial patch information on the CLI, but I can't figure out how to include it in my Zsh. 

Any thoughts on this?
[link](https://unix.stackexchange.com/questions/293119/conditional-prompt-for-mercurial?newreg=bbcd2eb18f714a6d90bbee75ac468227)

```
hg_ps1() {
    hg prompt " ({patch})" 2> /dev/null
}
export PS1='$ \W$(hg_ps1):
```
I'd love to be able to track patches and which one is at the tip, etc. I think anyone who did what you did is probably interested and so I thought I'd push this query up to you as a likely far senior coder to me; I'm in my first year, so legitimately you are more skilled than me.

**Comment by iarkhanhelsky** [comment]
Hi! It's pretty easy to convert your example to zsh and here it is:

```zsh
function hg_ps1() {
    echo `hg prompt " ({patch})"`
}

export PS1='$ %1~ $(hg_ps1):
```
Yet shell feels slow and unresponsive because it calls `hg` and it is quite slow. And you need [hg-prompt](https://bitbucket.org/sjl/hg-prompt) extension of course to get this working.

**Comment by misterhtmlcss** [comment]
Hi @iarkhanhelsky sorry for the delay. Your email notification got burried. When you closed it, then I found you. Thank you for your answer. I'm not entirely certain how to apply your solution to what I have. I am not a bash buy and what you wrote is simple and elegant, but to me I won't know where to place it.

I'm using the Obraun theme and my code in the theme is:
```
if [ "$USER" = "root" ]; then CARETCOLOR="red"; else CARETCOLOR="blue"; fi

local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%})"

PROMPT='%{$fg[green]%}[%*]%{$reset_color%} %{$fg_no_bold[cyan]%}%n %{${fg_bold[blue]}%}%{$fg_no_bold[magenta]%}➜%{$reset_color%} %{${fg[green]}%}%3~ $(git_prompt_info)$(hg_prompt_info "{patch}")%{${fg_bold[$CARETCOLOR]}%}»%{${reset_color}%} '

RPS1="${return_code}"

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[red]%}‹"
ZSH_THEME_GIT_PROMPT_SUFFIX="› %{$reset_color%}"

ZSH_THEME_HG_PROMPT_PREFIX="%{$fg_bold[magenta]%}hg:(%{$fg[red]%}"
ZSH_THEME_HG_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_HG_PROMPT_DIRTY="%{$fg[magenta]%}) %{$fg[yellow]%}✗%{$reset_color%}"
ZSH_THEME_HG_PROMPT_CLEAN="%{$fg[magenta]%})"
```
I super appreciate your feedback and I'm thankful to have it, but sadly I'm not sure where to drop it. Perhaps a tiny bit more guidance? I've included my code assuming the addition you suggest will get dropped into this mess some where. FYI I did not write this code I simply smashed together two other people's code and found I made progress, but couldn't figure out how to get the `patch` part in too.

Please and thank you!!

**Comment by iarkhanhelsky** [comment]
Hi again! 

It's super simple. Look at looooong string assigned to `PROMPT`. Something called `hg_prompt_info` already here: `$(hg_prompt_info "{patch}")`.  I don't know what it is excactly but it looks like something you looking for. So you already have function call with same parameter (`{patch}`). You just need to ensure if this `hg_prompt_info` really works. Or replace with my function from answer above. 

Try to comment this `PROMPT` and define your own more simple `PROMPT` just to see how things work.

Try this for start:
```shell
function hg_ps1() {
    echo `hg prompt " ({patch})"`
}

export PROMPT='$ %1~ $(hg_ps1):'
```

You can change your `.zshrc` in your favorite editor and just source it any time you need to apply changes with following command in your terminal:

```
$ source ~/.zshrc
```

Cheers!
